### Arrays

In [1]:
zeros(Integer,10,10)

10×10 Array{Integer,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [2]:
zeros(Float64,3,4)

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [6]:
rand(5,7)

5×7 Array{Float64,2}:
 0.992688  0.430544  0.438904   0.711923  0.806411  0.617924  0.241829
 0.285019  0.465798  0.0970627  0.56812   0.297113  0.130767  0.682516
 0.973391  0.122915  0.779567   0.265197  0.243599  0.107988  0.64645 
 0.698684  0.162023  0.919314   0.860688  0.333496  0.499629  0.570466
 0.79143   0.552429  0.865495   0.531719  0.09325   0.10679   0.350707

In [7]:
ones(Float64,3,4)

3×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0