## Arrays

In [1]:
zeros(Integer,10,10)

10×10 Array{Integer,2}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

In [2]:
zeros(Float64,3,4)

3×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [6]:
rand(5,7)

5×7 Array{Float64,2}:
 0.992688  0.430544  0.438904   0.711923  0.806411  0.617924  0.241829
 0.285019  0.465798  0.0970627  0.56812   0.297113  0.130767  0.682516
 0.973391  0.122915  0.779567   0.265197  0.243599  0.107988  0.64645 
 0.698684  0.162023  0.919314   0.860688  0.333496  0.499629  0.570466
 0.79143   0.552429  0.865495   0.531719  0.09325   0.10679   0.350707

In [7]:
ones(Float64,3,4)

3×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

### The following are comprehensions
----

In [1]:
[(-1)^n for n=0:9]

10-element Array{Int64,1}:
  1
 -1
  1
 -1
  1
 -1
  1
 -1
  1
 -1

In [2]:
[m+n for m=1:8, n=1:7]

8×7 Array{Int64,2}:
 2   3   4   5   6   7   8
 3   4   5   6   7   8   9
 4   5   6   7   8   9  10
 5   6   7   8   9  10  11
 6   7   8   9  10  11  12
 7   8   9  10  11  12  13
 8   9  10  11  12  13  14
 9  10  11  12  13  14  15

In [18]:
[m+n+k for m=0:5, n=0:5, k=0:5]

6×6×6 Array{Int64,3}:
[:, :, 1] =
 0  1  2  3  4   5
 1  2  3  4  5   6
 2  3  4  5  6   7
 3  4  5  6  7   8
 4  5  6  7  8   9
 5  6  7  8  9  10

[:, :, 2] =
 1  2  3  4   5   6
 2  3  4  5   6   7
 3  4  5  6   7   8
 4  5  6  7   8   9
 5  6  7  8   9  10
 6  7  8  9  10  11

[:, :, 3] =
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

[:, :, 4] =
 3  4   5   6   7   8
 4  5   6   7   8   9
 5  6   7   8   9  10
 6  7   8   9  10  11
 7  8   9  10  11  12
 8  9  10  11  12  13

[:, :, 5] =
 4   5   6   7   8   9
 5   6   7   8   9  10
 6   7   8   9  10  11
 7   8   9  10  11  12
 8   9  10  11  12  13
 9  10  11  12  13  14

[:, :, 6] =
  5   6   7   8   9  10
  6   7   8   9  10  11
  7   8   9  10  11  12
  8   9  10  11  12  13
  9  10  11  12  13  14
 10  11  12  13  14  15

### Accessing elements of an array
----

In [19]:
x=collect(5:15)

11-element Array{Int64,1}:
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15

In [20]:
x[5]

9

In [21]:
x[2:5]

4-element Array{Int64,1}:
 6
 7
 8
 9

In [23]:
x[3:end-3]

6-element Array{Int64,1}:
  7
  8
  9
 10
 11
 12

In [24]:
x[[5,1,3]]

3-element Array{Int64,1}:
 9
 5
 7

In [25]:
A=[i+j for i=1:4, j=1:5]

4×5 Array{Int64,2}:
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8
 5  6  7  8  9

In [26]:
A[3,2]

5

In [32]:
# Get 4th col of A
A[:,4]

4-element Array{Int64,1}:
 5
 6
 7
 8

In [39]:
# Get 3rd and 4th rows of A
A[3:4,:]

2×5 Array{Int64,2}:
 4  5  6  7  8
 5  6  7  8  9

### Common Operations on Matrices
----

In [53]:
A=[1 2 3 4;
   2 3 4 5;
   9 -3 8 -2;
   -3 7 4 9]

4×4 Array{Int64,2}:
  1   2  3   4
  2   3  4   5
  9  -3  8  -2
 -3   7  4   9

In [57]:
B=[-4 5 7 -2]

1×4 Array{Int64,2}:
 -4  5  7  -2

In [59]:
B*A

1×4 Array{Int64,2}:
 75  -28  56  -23

In [61]:
# Element by Element Multiplication
B.*A

4×4 Array{Int64,2}:
  -4   10  21   -8
  -8   15  28  -10
 -36  -15  56    4
  12   35  28  -18

In [65]:
# Square of the elements of a Matrix
C=[1 2 3 4;2 3 4 5;3 4 5 6;4 5 6 7]
sqrt(C)

4×4 Array{Float64,2}:
 1.0      1.41421  1.73205  2.0    
 1.41421  1.73205  2.0      2.23607
 1.73205  2.0      2.23607  2.44949
 2.0      2.23607  2.44949  2.64575

### Other Operations on Arrays
----

In [66]:
x=collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [67]:
sum(x)

55

In [68]:
sum(1:10)

55

In [69]:
@time sum(x)

  0.000008 seconds (130 allocations: 7.719 KB)


55

In [70]:
@time sum(1:10)

  0.000004 seconds (5 allocations: 192 bytes)


55

In [72]:
@time sum(collect(1:10^8))

 14.487804 seconds (10 allocations: 762.940 MB, 97.19% gc time)


5000000050000000

In [73]:
@time sum(1:10^8)

  0.000006 seconds (7 allocations: 224 bytes)


5000000050000000

In [78]:
@time sum(1:BigInt(10)^35)

  0.000033 seconds (48 allocations: 1.273 KB)


5000000000000000000000000000000000050000000000000000000000000000000000

In [79]:
prod([2,9,10,4])

720

### Mapping Elements of an Array
----

In [123]:
x=[3,9,-4,2]

4-element Array{Int64,1}:
  3
  9
 -4
  2

In [86]:
map(t->t^3+1,x)

4-element Array{Int64,1}:
  28
 730
 -63
   9

In [87]:
list=collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [91]:
x=map(t->t*2,list)

5-element Array{Int64,1}:
  2
  4
  6
  8
 10

In [128]:
y=map(t->2*t+1,list)

5-element Array{Int64,1}:
  3
  5
  7
  9
 11

In [129]:
z=map(t->Int(sinpi(0.5*t)),list)

5-element Array{Int64,1}:
  1
  0
 -1
  0
  1

In [142]:
list,x,y,z

([1,2,3,4,5],[3,9,-4,2],[3,5,7,9,11],[1,0,-1,0,1])

### Reducing an Array
----

In [133]:
A=collect(1:3:16)

6-element Array{Int64,1}:
  1
  4
  7
 10
 13
 16

In [136]:
reduce(+,0,A)

51

In [143]:
sum(A)

51

In [147]:
reduce(string,"",["J","u","l","i","a"])

"Julia"

In [153]:
mapreduce(t->t^2,+,0,[1,2,3])

14

*The following is the geometric mean*

In [156]:
d=[1,2,3,4,5]
len=length(d)
mapreduce(t->t^(1/len),*,1,d)

2.605171084697352

*Sum has this built-in as well*

In [157]:
sum(t->t^2,[1,2,3])

14

*Recall this `is_happy` function*

In [163]:
function split_digits(n::Number)
    # function here
end

function is_happy(n::Integer)
    n==1?true:n==4?false:is_happy(sum(t->t^2,split_digits(n)))
end

is_happy (generic function with 1 method)

In [162]:
is_happy(100)

LoadError: LoadError: StackOverflowError:
while loading In[162], in expression starting on line 1

In [ ]:
filter(is_happy,1:100)