## Project 1: Google Distance Matrix

In [1]:
f=open("distances.json","r")
dist=JSON.parse(f)
close(f)

In [2]:
dist

Dict{String,Any} with 4 entries:
  "status"                => "OK"
  "destination_addresses" => Any["Fitchburg, MA 01420, USA","Boston, MA, USA","…
  "rows"                  => Any[Dict{String,Any}(Pair{String,Any}("elements",A…
  "origin_addresses"      => Any["Fitchburg, MA 01420, USA","Boston, MA, USA","…

In [3]:
dist["destination_addresses"]

3-element Array{Any,1}:
 "Fitchburg, MA 01420, USA"
 "Boston, MA, USA"         
 "New York, NY, USA"       

The following is the distance in meters from Fitchburg MA to Boston MA

In [4]:
f2b=dist["rows"][1]["elements"][2]["distance"]["value"]

85137

In [5]:
f2b*0.00062137 # convert to miles

52.901577689999996

In [6]:
dist_arr = zeros(Float64,3,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [7]:
for i=1:3
    for j=1:3
        dist_arr[i,j] = dist["rows"][i]["elements"][j]["distance"]["value"]
    end
end
dist_arr

3×3 Array{Float64,2}:
      0.0   85137.0  328495.0
  75726.0       0.0  346648.0
 326394.0  346499.0       0.0

In [8]:
avidia_arr = zeros(Float64,10,10)

10×10 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [15]:
f=open("avidia.json","r")
avidia_dist=JSON.parse(f)
close(f)

In [16]:
info

Dict{String,Any} with 4 entries:
  "status"                => "OK"
  "destination_addresses" => Any["42 Main St, Hudson, MA 01749, USA","17 Pope S…
  "rows"                  => Any[Dict{String,Any}(Pair{String,Any}("elements",A…
  "origin_addresses"      => Any["42 Main St, Hudson, MA 01749, USA","17 Pope S…

In [17]:
println("Address of Primary Operations: ",info["destination_addresses"][4])

Address of Primary Operations: 100 E Main St, Westborough, MA 01581, USA


In [18]:
info["rows"];

In [20]:
for i=1:10
    for j=1:10
        avidia_arr[i,j] = avidia_dist["rows"][i]["elements"][j]["distance"]["value"]*0.00062137
    end
end
avidia_arr

10×10 Array{Float64,2}:
  0.0         0.348589  11.1486    11.2232    …   4.24209   7.1936   12.6443 
  0.0652439   0.0       11.2139    11.2884        4.30734   7.25884  12.7095 
 10.8684     11.12       0.0        0.200703      5.84398   4.42602   7.1122 
 10.9423     11.1946     0.200703   0.0           5.91855   4.62672   7.3129 
  9.22797     9.3336    18.6535    18.7275       15.2851   10.4589   11.5569 
  0.891666    1.14332   10.2358    10.3098    …   3.32868   6.95189  11.7308 
 13.3253     13.4315    22.7515    22.8254       19.3824   27.7032   22.8844 
  4.23091     4.48318    5.84398    5.91855       0.0       6.55856  14.4102 
  7.16999     7.42226    4.60187    4.80319       6.3591    0.0       4.49251
 12.1739     12.4255     7.10972    7.31042      13.595     4.49251   0.0    