# Project 1: Traveling Salesperson Problem (TSP)<br><small>Joshua Nasiatka (2016.11.13)

This problem solves a real-world Traveling Salesperson Problem (TSP) using distance data. We will find the shortest total path between the Massachusetts cities/towns: Boston, Fall River, Fitchburg, Lowell, North Adams, Springfield and Worcester. Follow these steps to do this:  

**( a ) Use the brute force algorithm that goes through each path to determine the shortest total distance. Find the distance and write down the path as it goes through each town. Start and end with Fitchburg and write down the town names of the shortest path.**

In [1]:
f=open("cities.json","r")
dist=JSON.parse(f)
close(f)

In [2]:
dist

Dict{String,Any} with 4 entries:
  "status"                => "OK"
  "destination_addresses" => Any["Fitchburg, MA 01420, USA","Boston, MA, USA","…
  "rows"                  => Any[Dict{String,Any}(Pair{String,Any}("elements",A…
  "origin_addresses"      => Any["Fitchburg, MA 01420, USA","Boston, MA, USA","…

In [3]:
dist["origin_addresses"]

7-element Array{Any,1}:
 "Fitchburg, MA 01420, USA"  
 "Boston, MA, USA"           
 "Fall River, MA, USA"       
 "Lowell, MA, USA"           
 "North Adams, MA 01247, USA"
 "Springfield, MA, USA"      
 "Worcester, MA, USA"        

In [4]:
dist["destination_addresses"]

7-element Array{Any,1}:
 "Fitchburg, MA 01420, USA"  
 "Boston, MA, USA"           
 "Fall River, MA, USA"       
 "Lowell, MA, USA"           
 "North Adams, MA 01247, USA"
 "Springfield, MA, USA"      
 "Worcester, MA, USA"        

In [5]:
dist_arr = zeros(Float64,7,7)

7×7 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [6]:
for i=1:7
    for j=1:7
        dist_arr[i,j] = dist["rows"][i]["elements"][j]["distance"]["value"]
    end
end
dist_arr

7×7 Array{Float64,2}:
      0.0   85137.0  135492.0   53425.0  139844.0  128185.0   44788.0
  75726.0       0.0   84289.0   48475.0  210273.0  146338.0   76529.0
 133613.0   83508.0       0.0  123995.0  253265.0  164325.0   90948.0
  50558.0   48841.0  123976.0       0.0  185106.0  149465.0   66068.0
 140339.0  218897.0  272686.0  187185.0       0.0  118706.0  192364.0
 126666.0  146771.0  164324.0  150804.0   98402.0       0.0   84002.0
  43833.0   75949.0   91668.0   67972.0  173301.0   84361.0       0.0

In [7]:
using Combinatorics

In [21]:
# function check_distance(a,b,dists)
#     local d = abs(dists[1,b]-dists[1,a])
#     d
# end

function TSP(dists::Array{Float64,2}, dist)
    local d = dists
    local size = length(dist_arr[1,:])
    local a = 0
    local short = 9999999
    local sp = []
    local sp2 = []
    for i=1:size
        local s = 0
        for j=1:size
            s += d[i,j]
            push!(sp,d[i,j])
            push!(sp2,dist["destination_addresses"][j])
        end
        if s < short
            short = s
        else
            sp = []
            sp2 = []
        end
        s = 0
    end
    sp2
end

function TSP_BF(dists::Array{Float64,2})
    local d = dists
    local size = length(dist_arr[1,:])
    local perms = zeros(Float64, 7)
    perms
end

TSP_BF (generic function with 1 method)

In [22]:
# TSP(dist_arr, dist)
TSP_BF(dist_arr)

7-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [53]:
darr = map(z->z=1:7,dist["destination_addresses"][z]);
collect(permutations(dist["destination_addresses"]));
darr

LoadError: LoadError: UndefVarError: z not defined
while loading In[53], in expression starting on line 1